name: NoMoreCombatLog
version: '1.0-SNAPSHOT'
main: org.mikrowellentoast.NMCL.NoMoreCombatLog
api-version: '1.21.10'
authors: [ mikrowellentoast ]
description: A simple and configurable Paper plugin that prevents players from combat logging.
